site_name: jsonl
site_description: "Documentation for the jsonl Python library"
site_url: "https://github.com/rmoralespp/jsonl"
repo_url: https://github.com/rmoralespp/jsonl
repo_name: jsonl
theme:
  name: readthedocs
  custom_dir: 'docs'
markdown_extensions:
  admonition: {}
nav:
  - Introduction: index.md
  - API usage:
      - Load jsonlines file: load.md
      - Load archive files: load_archive.md
      - Dump to a jsonlines file: dump.md
      - Dump to multiple jsonlines files: dump_fork.md
      - Dump archive files: dump_archive.md
      - Dump to a string: dumps.md
  - Changes: changes.md
